name: Inital tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0 


    - name: Verify PHP Syntax
      run: |
        for file in $(find . -name "*.php"); do
          php -l $file;
        done

    - name: Validate HTML
      run: |
        sudo apt-get install -y tidy
        for file in $(find . -name "*.html"); do
          tidy -e $file;
        done

    
