name: Run PHPUnit Tests

on:
  push:
    branches:
      - main

jobs:
  phpunit_tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2  # Or whichever PHP version your project requires
        extensions: mbstring, pdo, pdo_mysql  # Include any PHP extensions your tests need

    # Step 3: Install dependencies
    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    # Step 4: Run PHPUnit tests
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --coverage-text
