name: Validate Composer and Run PHPUnit Tests

on:
  push:
    branches:
      - main

jobs:
  phpunit_tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, pdo_mysql

    # Step 3: Validate composer.json and composer.lock
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    # Step 4: Cache Composer packages
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # Step 5: Remove vendor directory (optional)
    - name: Remove vendor directory
      run: rm -rf vendor

    # Step 6: Install dependencies
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress -vvv

    # Step 7: Dump autoload
    - name: Dump autoload
      run: composer dump-autoload

    # Step 8: Check vendor directory
    - name: List vendor directory
      run: ls -la vendor/phpunit/phpunit/src/

    # Step 9: Run PHPUnit tests
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --coverage-text -v
